# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1f1fdf5e8eeef70b2da5c05086e93baf604562370134f6fdb3014a80487610ebedcd5eb6a0d13cf686b11a6fa0a980d299deeac7b991854e9607b2acc928c3

test:
  secret_key_base: 707149dbd7459ab72f3dc524e68280b19eade098663d631c4c69b9e4926964906a29dbd91d5b5c31b79d6ce4a7ec9a5c14b42f7a837a09e87edaceb8e79270ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
